### ISSUE TITLE
Feature: Change repository name

### ISSUE THREAD

**Issue by pangolp** [Kaev/BetterItemReloading#4]
### Describe your feature request or suggestion in detail

It should not pass the compilation tests, because the name does not respect the format it must have in the emulator API.

### Describe a possible solution to your feature or suggestion in detail

The repository should be called: `mod-better-item-reloading`, in the same way as it is currently found in the AzerothCore community.

**Comment by Kaev** [comment]
Updated the name. Hope that was right? :)

**Comment by pangolp** [comment]
> Updated the name. Hope that was right? :)

It looks like it is. That would be enough. Thank you.
